+++
++
Enter Reason for Late Arrival:
Sick
Doctor/Dentist Appointment
Unexcused
Late Bus
Religious Reason
Transportation
College Visit
++
Enter note location:
Currently in the basket
Emailed
In the basket within the next 3 days
No note
+++
++
Enter reason for leaving:
Sick
Doctor/Dentist Appointment
Religious Reason
College Visit
++
Enter who you were excused by: 
Health Room
Parent
++
Enter note location:
Currently in the basket
Emailed



