+++
++
What is your reason for late arrival?
Sick
Doctor/Dentist Appointment
Unexcused
Late Bus
Religious Reason
Transportation
College Visit
++
Where is your note?
Currently in the basket
Emailed
In the basket within the next 3 days
No note
+++
++
What is your reason for leaving?
Sick
Doctor/Dentist Appointment
Religious Reason
College Visit
++
Who were you excused by?
Health Room
Parent
++
Where is your note?
Currently in the basket
Emailed
In the basket within the next 3 days


